# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import elecont_pb2 as elecont__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in elecont_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ElecontStub(object):
    """*
    Сервис протокола Elecont.
    Файл содержит protobuf схему данных для Эликонт-КС версий 2.X.X для обеспечения информационного обмена со сторонними программными решениями.
    Дата: 25.09.2025
    (C) 2025 АО "ЭЛАРА". Все права защищены.

    АО "ЭЛАРА" предоставляет данный файл как открытый элемент программного продукта Эликонт-КС.
    Внесение изменений в данный файл может нарушить работоспособность производного кода и связанных с ним пользовательских решений.
    АО "ЭЛАРА" не несёт ответственность за программный код, созданный сторонними разработчиками для обеспечения информационного обмена с Эликонт-КС и использующий данный файл.

    Лицензирование:
    Откройте раздел "Лицензия" в документации к продукту для получения подробной информации.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/elecont.Elecont/GetState',
                request_serializer=elecont__pb2.Empty.SerializeToString,
                response_deserializer=elecont__pb2.State.FromString,
                _registered_method=True)
        self.GetSignalsById = channel.unary_unary(
                '/elecont.Elecont/GetSignalsById',
                request_serializer=elecont__pb2.SignalsId.SerializeToString,
                response_deserializer=elecont__pb2.SignalPool.FromString,
                _registered_method=True)
        self.GetSignalsByGuid = channel.unary_unary(
                '/elecont.Elecont/GetSignalsByGuid',
                request_serializer=elecont__pb2.SignalsGuid.SerializeToString,
                response_deserializer=elecont__pb2.SignalPool.FromString,
                _registered_method=True)
        self.GetSignalsByType = channel.unary_unary(
                '/elecont.Elecont/GetSignalsByType',
                request_serializer=elecont__pb2.ElecontSignalType.SerializeToString,
                response_deserializer=elecont__pb2.SignalPool.FromString,
                _registered_method=True)
        self.GetCommandsById = channel.unary_unary(
                '/elecont.Elecont/GetCommandsById',
                request_serializer=elecont__pb2.SignalsId.SerializeToString,
                response_deserializer=elecont__pb2.CommandPool.FromString,
                _registered_method=True)
        self.GetCommandsByGuid = channel.unary_unary(
                '/elecont.Elecont/GetCommandsByGuid',
                request_serializer=elecont__pb2.SignalsGuid.SerializeToString,
                response_deserializer=elecont__pb2.CommandPool.FromString,
                _registered_method=True)
        self.GetCommandsByType = channel.unary_unary(
                '/elecont.Elecont/GetCommandsByType',
                request_serializer=elecont__pb2.ElecontSignalType.SerializeToString,
                response_deserializer=elecont__pb2.CommandPool.FromString,
                _registered_method=True)
        self.CreateEmptyReport = channel.unary_unary(
                '/elecont.Elecont/CreateEmptyReport',
                request_serializer=elecont__pb2.ReportId.SerializeToString,
                response_deserializer=elecont__pb2.Result.FromString,
                _registered_method=True)
        self.DeleteReport = channel.unary_unary(
                '/elecont.Elecont/DeleteReport',
                request_serializer=elecont__pb2.ReportId.SerializeToString,
                response_deserializer=elecont__pb2.Result.FromString,
                _registered_method=True)
        self.DeleteAllReport = channel.unary_unary(
                '/elecont.Elecont/DeleteAllReport',
                request_serializer=elecont__pb2.Empty.SerializeToString,
                response_deserializer=elecont__pb2.Result.FromString,
                _registered_method=True)
        self.AddSignalToReport = channel.unary_unary(
                '/elecont.Elecont/AddSignalToReport',
                request_serializer=elecont__pb2.Report.SerializeToString,
                response_deserializer=elecont__pb2.Result.FromString,
                _registered_method=True)
        self.GetSignalsByReport = channel.unary_unary(
                '/elecont.Elecont/GetSignalsByReport',
                request_serializer=elecont__pb2.ReportId.SerializeToString,
                response_deserializer=elecont__pb2.SignalPool.FromString,
                _registered_method=True)
        self.GetChangedSignals = channel.unary_unary(
                '/elecont.Elecont/GetChangedSignals',
                request_serializer=elecont__pb2.Empty.SerializeToString,
                response_deserializer=elecont__pb2.SignalPool.FromString,
                _registered_method=True)
        self.GetChangedSignalsByReport = channel.unary_unary(
                '/elecont.Elecont/GetChangedSignalsByReport',
                request_serializer=elecont__pb2.ReportId.SerializeToString,
                response_deserializer=elecont__pb2.SignalPool.FromString,
                _registered_method=True)
        self.GetAllSignals = channel.unary_unary(
                '/elecont.Elecont/GetAllSignals',
                request_serializer=elecont__pb2.Empty.SerializeToString,
                response_deserializer=elecont__pb2.SignalPool.FromString,
                _registered_method=True)
        self.GetAllCommands = channel.unary_unary(
                '/elecont.Elecont/GetAllCommands',
                request_serializer=elecont__pb2.Empty.SerializeToString,
                response_deserializer=elecont__pb2.CommandPool.FromString,
                _registered_method=True)
        self.SetSignals = channel.unary_unary(
                '/elecont.Elecont/SetSignals',
                request_serializer=elecont__pb2.SignalPool.SerializeToString,
                response_deserializer=elecont__pb2.Result.FromString,
                _registered_method=True)
        self.GetSignalsStream = channel.unary_stream(
                '/elecont.Elecont/GetSignalsStream',
                request_serializer=elecont__pb2.Empty.SerializeToString,
                response_deserializer=elecont__pb2.Signals.FromString,
                _registered_method=True)
        self.GetCommandsStream = channel.unary_stream(
                '/elecont.Elecont/GetCommandsStream',
                request_serializer=elecont__pb2.Empty.SerializeToString,
                response_deserializer=elecont__pb2.Commands.FromString,
                _registered_method=True)
        self.GetAllObjectsData = channel.unary_unary(
                '/elecont.Elecont/GetAllObjectsData',
                request_serializer=elecont__pb2.Empty.SerializeToString,
                response_deserializer=elecont__pb2.Objects.FromString,
                _registered_method=True)
        self.GetSignalByGuid = channel.unary_unary(
                '/elecont.Elecont/GetSignalByGuid',
                request_serializer=elecont__pb2.Guid.SerializeToString,
                response_deserializer=elecont__pb2.Signal.FromString,
                _registered_method=True)
        self.GetCommandByGuid = channel.unary_unary(
                '/elecont.Elecont/GetCommandByGuid',
                request_serializer=elecont__pb2.Guid.SerializeToString,
                response_deserializer=elecont__pb2.Command.FromString,
                _registered_method=True)
        self.SetSignal = channel.unary_unary(
                '/elecont.Elecont/SetSignal',
                request_serializer=elecont__pb2.Signal.SerializeToString,
                response_deserializer=elecont__pb2.Result.FromString,
                _registered_method=True)
        self.SetCommand = channel.unary_unary(
                '/elecont.Elecont/SetCommand',
                request_serializer=elecont__pb2.Command.SerializeToString,
                response_deserializer=elecont__pb2.Result.FromString,
                _registered_method=True)
        self.SetSignalsStream = channel.stream_unary(
                '/elecont.Elecont/SetSignalsStream',
                request_serializer=elecont__pb2.Signals.SerializeToString,
                response_deserializer=elecont__pb2.Empty.FromString,
                _registered_method=True)
        self.SetCommandsStream = channel.stream_unary(
                '/elecont.Elecont/SetCommandsStream',
                request_serializer=elecont__pb2.Commands.SerializeToString,
                response_deserializer=elecont__pb2.Empty.FromString,
                _registered_method=True)


class ElecontServicer(object):
    """*
    Сервис протокола Elecont.
    Файл содержит protobuf схему данных для Эликонт-КС версий 2.X.X для обеспечения информационного обмена со сторонними программными решениями.
    Дата: 25.09.2025
    (C) 2025 АО "ЭЛАРА". Все права защищены.

    АО "ЭЛАРА" предоставляет данный файл как открытый элемент программного продукта Эликонт-КС.
    Внесение изменений в данный файл может нарушить работоспособность производного кода и связанных с ним пользовательских решений.
    АО "ЭЛАРА" не несёт ответственность за программный код, созданный сторонними разработчиками для обеспечения информационного обмена с Эликонт-КС и использующий данный файл.

    Лицензирование:
    Откройте раздел "Лицензия" в документации к продукту для получения подробной информации.

    """

    def GetState(self, request, context):
        """*
        Получить состояние сервиса.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignalsById(self, request, context):
        """*
        Получить пул сигналов по заданным идентификаторам. Если сигналов с заданными идентификаторами не окажется, то вернётся пустой пул.
        Целочисленные идентификаторы сигналов можно получить, например, вызвав GetAllSignals или GetAllObjectsData
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignalsByGuid(self, request, context):
        """*
        Получить пул сигналов по заданным GUID сигналов. Если сигналов с заданными GUID не окажется, то вернётся пустой пул.
        GUID сигналов можно получить, например, вызвав GetAllSignals или GetAllObjectsData
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignalsByType(self, request, context):
        """*
        Получить пул сигналов по заданному типу сигналов. Если сигналов с заданным типом не окажется, то вернётся пустой пул.
        Типы сигналов заданы в определении ElecontSignalType в соответствующем перечислении
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommandsById(self, request, context):
        """*
        Получить пул команд по заданным идентификаторам. Если команд с заданными идентификаторами не окажется, то вернётся пустой пул.
        Целочисленные идентификаторы команд можно получить, например, вызвав GetAllCommands или GetAllObjectsData
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommandsByGuid(self, request, context):
        """*
        Получить пул команд по заданным GUID команд. Если команд с заданными GUID не окажется, то вернётся пустой пул.
        GUID команд можно получить, например, вызвав GetAllCommands или GetAllObjectsData
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommandsByType(self, request, context):
        """*
        Получить пул команд по заданному типу команд. Если команд с заданным типом не окажется, то вернётся пустой пул.
        Типы команд заданы в определении в ElecontSignalType в соответствующем перечислении
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEmptyReport(self, request, context):
        """*
        Создать пустой отчёт (подписку) с заданным идентификатором.
        По указанному идентификатору в дальнйшем можно оперировать с отчётом. Например, получить сигналы, входящие в данный отчёт
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteReport(self, request, context):
        """*
        Удалить отчёт с заданным идентификатором
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAllReport(self, request, context):
        """*
        Удалить все существующие отчёты (подписки)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSignalToReport(self, request, context):
        """*
        Добавить сигналы в отчёт (подписку).
        В запросе внутри сообщения Report, помимо идентификаторов сигналов, требуется указывать идентификатор существующего отчёта. Его нужно предварительно создать функцией CreateEmptyReport
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignalsByReport(self, request, context):
        """*
        Получить пул сигналов из отчёта. Если для отчёта не заданы сигналы, то вернётся пустой пул.
        В запросе требуется указать идентификатор существующего отчёта
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChangedSignals(self, request, context):
        """*
        Получить пул изменённых сигналов с момента предыдущего вызова данной функции. Если ни один сигнал не менял значение, то вернётся пустой пул.
        Данную функцию нельзя использовать совместно с GetAllSignals
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChangedSignalsByReport(self, request, context):
        """*
        Получить пул изменённых сигналов с момента предыдущего вызова данной функции из заданного отчёта. Если ни один сигнал не менял значение, то вернётся пустой пул.

        [ВНИМАНИЕ]: На текущий момент работает аналогично GetSignalsByReport. Не рекомендуется для использования сторонними приложениями на текущем этапе
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllSignals(self, request, context):
        """*
        Получить пул всех сигналов из текущей конфигурации КС. 
        Для больших конфигураций с большим количеством сигналов этот вызов может быть ресурсоёмким, поэтому его рекомендуется его использовать с осторожностью
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllCommands(self, request, context):
        """*
        Получить пул всех команд из текущей конфигурации КС. 
        Для больших конфигураций с большим количеством команд этот вызов может быть ресурсоёмким, поэтому его рекомендуется его использовать с осторожностью
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSignals(self, request, context):
        """*
        Задать значения сигналов в КС из заданного пула. Значения будут установленты только тем сигналам, идентификаторы которых существуют в текущей конфигурации КС
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignalsStream(self, request, context):
        """*
        Получить все сигналы из текущей конфигурации КС в виде потока. 
        Обратите внимание, что внутри потока передаются сообщения Signal. Это облегчённая версия представления данных по отношению к SignalPool
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommandsStream(self, request, context):
        """*
        Получить все команды из текущей конфигурации КС в виде потока. 
        Обратите внимание, что внутри потока передаются сообщения Command. Это облегчённая версия представления данных по отношению к CommandPool
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllObjectsData(self, request, context):
        """*
        Получить данные всех объектов из текущей конфигурации КС. 
        Данный вызов имеет смысл производить только один раз, так как данные текущей конфигурации КС не изменяются до тех пор, пока её не обновять через api gateway. Например, это сделает пользователь через Конфигуратор
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignalByGuid(self, request, context):
        """*
        Получить сигнал по заданному GUID. Если сигнала с заданными GUID не окажется в текущей конфигурации КС, то вернётся сообщение Signal с данными по умолчанию.
        Является обегчённой версией функции GetSignalsByGuid. Возвращает простое по структуре сообщение Signal
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommandByGuid(self, request, context):
        """*
        Получить команду по заданному GUID. Если сигнала с заданными GUID не окажется в текущей конфигурации КС, то вернётся сообщение Command с данными по умолчанию.
        Является обегчённой версией функции GetCommandsByGuid. Возвращает простое по структуре сообщение Command
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSignal(self, request, context):
        """*
        Задать сигнал. Запрос должен содержать сообщение Signal с GUID, который существует в текущей конфигурации КС. Если сигнал с таким GUID не будет обраружен, то запрос выполнен не будет.
        Является обегчённой версией функции SetSignals. Принимает в качестве запроса простое по структуре сообщение Signal
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCommand(self, request, context):
        """*
        Задать команду. Запрос должен содержать сообщение Command с GUID, который существует в текущей конфигурации КС. Если команда с таким GUID не будет обраружена, то запрос выполнен не будет
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSignalsStream(self, request_iterator, context):
        """*
        Задать сигналы клиентским потоком. 
        Сообщения Signal в потоке должны содержать GUID, которые существует в текущей конфигурации КС. Если GUID какого-либо сигнала не будет обраружен, то для этого GUID данные сигнала заданы не будут.

        [ВНИМАНИЕ]: Функция не оттестирована. Не рекомендуется для использования сторонними приложениями на текущем этапе
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCommandsStream(self, request_iterator, context):
        """*
        Задать команды клиентским потоком. 
        Сообщения Command в потоке должны содержать GUID, которые существует в текущей конфигурации КС. Если GUID какой-либо команды не будет обраружен, то для этого GUID данные команды заданы не будут.

        [ВНИМАНИЕ]: Функция на текущий не работает и находится в разработке. Рассматривается целесообразность её реализации. Не рекомендуется для использования сторонними приложениями на текущем этапе
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ElecontServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=elecont__pb2.Empty.FromString,
                    response_serializer=elecont__pb2.State.SerializeToString,
            ),
            'GetSignalsById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSignalsById,
                    request_deserializer=elecont__pb2.SignalsId.FromString,
                    response_serializer=elecont__pb2.SignalPool.SerializeToString,
            ),
            'GetSignalsByGuid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSignalsByGuid,
                    request_deserializer=elecont__pb2.SignalsGuid.FromString,
                    response_serializer=elecont__pb2.SignalPool.SerializeToString,
            ),
            'GetSignalsByType': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSignalsByType,
                    request_deserializer=elecont__pb2.ElecontSignalType.FromString,
                    response_serializer=elecont__pb2.SignalPool.SerializeToString,
            ),
            'GetCommandsById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommandsById,
                    request_deserializer=elecont__pb2.SignalsId.FromString,
                    response_serializer=elecont__pb2.CommandPool.SerializeToString,
            ),
            'GetCommandsByGuid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommandsByGuid,
                    request_deserializer=elecont__pb2.SignalsGuid.FromString,
                    response_serializer=elecont__pb2.CommandPool.SerializeToString,
            ),
            'GetCommandsByType': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommandsByType,
                    request_deserializer=elecont__pb2.ElecontSignalType.FromString,
                    response_serializer=elecont__pb2.CommandPool.SerializeToString,
            ),
            'CreateEmptyReport': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEmptyReport,
                    request_deserializer=elecont__pb2.ReportId.FromString,
                    response_serializer=elecont__pb2.Result.SerializeToString,
            ),
            'DeleteReport': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteReport,
                    request_deserializer=elecont__pb2.ReportId.FromString,
                    response_serializer=elecont__pb2.Result.SerializeToString,
            ),
            'DeleteAllReport': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAllReport,
                    request_deserializer=elecont__pb2.Empty.FromString,
                    response_serializer=elecont__pb2.Result.SerializeToString,
            ),
            'AddSignalToReport': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSignalToReport,
                    request_deserializer=elecont__pb2.Report.FromString,
                    response_serializer=elecont__pb2.Result.SerializeToString,
            ),
            'GetSignalsByReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSignalsByReport,
                    request_deserializer=elecont__pb2.ReportId.FromString,
                    response_serializer=elecont__pb2.SignalPool.SerializeToString,
            ),
            'GetChangedSignals': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChangedSignals,
                    request_deserializer=elecont__pb2.Empty.FromString,
                    response_serializer=elecont__pb2.SignalPool.SerializeToString,
            ),
            'GetChangedSignalsByReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChangedSignalsByReport,
                    request_deserializer=elecont__pb2.ReportId.FromString,
                    response_serializer=elecont__pb2.SignalPool.SerializeToString,
            ),
            'GetAllSignals': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllSignals,
                    request_deserializer=elecont__pb2.Empty.FromString,
                    response_serializer=elecont__pb2.SignalPool.SerializeToString,
            ),
            'GetAllCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllCommands,
                    request_deserializer=elecont__pb2.Empty.FromString,
                    response_serializer=elecont__pb2.CommandPool.SerializeToString,
            ),
            'SetSignals': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSignals,
                    request_deserializer=elecont__pb2.SignalPool.FromString,
                    response_serializer=elecont__pb2.Result.SerializeToString,
            ),
            'GetSignalsStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSignalsStream,
                    request_deserializer=elecont__pb2.Empty.FromString,
                    response_serializer=elecont__pb2.Signals.SerializeToString,
            ),
            'GetCommandsStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCommandsStream,
                    request_deserializer=elecont__pb2.Empty.FromString,
                    response_serializer=elecont__pb2.Commands.SerializeToString,
            ),
            'GetAllObjectsData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllObjectsData,
                    request_deserializer=elecont__pb2.Empty.FromString,
                    response_serializer=elecont__pb2.Objects.SerializeToString,
            ),
            'GetSignalByGuid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSignalByGuid,
                    request_deserializer=elecont__pb2.Guid.FromString,
                    response_serializer=elecont__pb2.Signal.SerializeToString,
            ),
            'GetCommandByGuid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommandByGuid,
                    request_deserializer=elecont__pb2.Guid.FromString,
                    response_serializer=elecont__pb2.Command.SerializeToString,
            ),
            'SetSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSignal,
                    request_deserializer=elecont__pb2.Signal.FromString,
                    response_serializer=elecont__pb2.Result.SerializeToString,
            ),
            'SetCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCommand,
                    request_deserializer=elecont__pb2.Command.FromString,
                    response_serializer=elecont__pb2.Result.SerializeToString,
            ),
            'SetSignalsStream': grpc.stream_unary_rpc_method_handler(
                    servicer.SetSignalsStream,
                    request_deserializer=elecont__pb2.Signals.FromString,
                    response_serializer=elecont__pb2.Empty.SerializeToString,
            ),
            'SetCommandsStream': grpc.stream_unary_rpc_method_handler(
                    servicer.SetCommandsStream,
                    request_deserializer=elecont__pb2.Commands.FromString,
                    response_serializer=elecont__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elecont.Elecont', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('elecont.Elecont', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Elecont(object):
    """*
    Сервис протокола Elecont.
    Файл содержит protobuf схему данных для Эликонт-КС версий 2.X.X для обеспечения информационного обмена со сторонними программными решениями.
    Дата: 25.09.2025
    (C) 2025 АО "ЭЛАРА". Все права защищены.

    АО "ЭЛАРА" предоставляет данный файл как открытый элемент программного продукта Эликонт-КС.
    Внесение изменений в данный файл может нарушить работоспособность производного кода и связанных с ним пользовательских решений.
    АО "ЭЛАРА" не несёт ответственность за программный код, созданный сторонними разработчиками для обеспечения информационного обмена с Эликонт-КС и использующий данный файл.

    Лицензирование:
    Откройте раздел "Лицензия" в документации к продукту для получения подробной информации.

    """

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetState',
            elecont__pb2.Empty.SerializeToString,
            elecont__pb2.State.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignalsById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetSignalsById',
            elecont__pb2.SignalsId.SerializeToString,
            elecont__pb2.SignalPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignalsByGuid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetSignalsByGuid',
            elecont__pb2.SignalsGuid.SerializeToString,
            elecont__pb2.SignalPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignalsByType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetSignalsByType',
            elecont__pb2.ElecontSignalType.SerializeToString,
            elecont__pb2.SignalPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommandsById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetCommandsById',
            elecont__pb2.SignalsId.SerializeToString,
            elecont__pb2.CommandPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommandsByGuid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetCommandsByGuid',
            elecont__pb2.SignalsGuid.SerializeToString,
            elecont__pb2.CommandPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommandsByType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetCommandsByType',
            elecont__pb2.ElecontSignalType.SerializeToString,
            elecont__pb2.CommandPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEmptyReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/CreateEmptyReport',
            elecont__pb2.ReportId.SerializeToString,
            elecont__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/DeleteReport',
            elecont__pb2.ReportId.SerializeToString,
            elecont__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAllReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/DeleteAllReport',
            elecont__pb2.Empty.SerializeToString,
            elecont__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSignalToReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/AddSignalToReport',
            elecont__pb2.Report.SerializeToString,
            elecont__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignalsByReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetSignalsByReport',
            elecont__pb2.ReportId.SerializeToString,
            elecont__pb2.SignalPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChangedSignals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetChangedSignals',
            elecont__pb2.Empty.SerializeToString,
            elecont__pb2.SignalPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChangedSignalsByReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetChangedSignalsByReport',
            elecont__pb2.ReportId.SerializeToString,
            elecont__pb2.SignalPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllSignals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetAllSignals',
            elecont__pb2.Empty.SerializeToString,
            elecont__pb2.SignalPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetAllCommands',
            elecont__pb2.Empty.SerializeToString,
            elecont__pb2.CommandPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSignals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/SetSignals',
            elecont__pb2.SignalPool.SerializeToString,
            elecont__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignalsStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/elecont.Elecont/GetSignalsStream',
            elecont__pb2.Empty.SerializeToString,
            elecont__pb2.Signals.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommandsStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/elecont.Elecont/GetCommandsStream',
            elecont__pb2.Empty.SerializeToString,
            elecont__pb2.Commands.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllObjectsData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetAllObjectsData',
            elecont__pb2.Empty.SerializeToString,
            elecont__pb2.Objects.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignalByGuid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetSignalByGuid',
            elecont__pb2.Guid.SerializeToString,
            elecont__pb2.Signal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommandByGuid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetCommandByGuid',
            elecont__pb2.Guid.SerializeToString,
            elecont__pb2.Command.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/SetSignal',
            elecont__pb2.Signal.SerializeToString,
            elecont__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/SetCommand',
            elecont__pb2.Command.SerializeToString,
            elecont__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSignalsStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/elecont.Elecont/SetSignalsStream',
            elecont__pb2.Signals.SerializeToString,
            elecont__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCommandsStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/elecont.Elecont/SetCommandsStream',
            elecont__pb2.Commands.SerializeToString,
            elecont__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
